# Generated by Django 4.0.2 on 2022-02-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_post_meta_description_post_thubarahalli_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='post',
            name='categorys',
            field=models.ManyToManyField(blank=True, related_name='categorys', to='blog.category'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
