# Generated by Django 4.0.2 on 2022-02-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_imagetable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='thubarahalli',
            field=models.CharField(max_length=250),
        ),
    ]
